#nome da pipeline
name: Run Basic Testers

#Em que momento ela será executada
on: 
    pull_request:
        branches: [ main ]

jobs: 
    #O que será feito na pipeline, só teremos um job
    cypress-run:
        #máquina que será executada
        runs-on: ubuntu-latest

        #Passo a passo para rodar os testes
        steps:
            #Primeiro passo é fazer o checkout do código
            - name: Checkout/Clone do projeto
              uses: actions/checkout@v3
            - name: Run testers
              uses: cypress-io/github-action@v5
              with:
                    record: true
              env: 
                    #Variáveis de ambiente para o Cypress
                    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}